server:
  port: 8083
  servlet:
    context-path: /market-service

spring:

  application:
    name: market-service
    profiles:
      active: 'local'

  data:
    mongodb:
      uri: mongodb://test123:test123@localhost:27019/market-service-db

hosts:
  auth-service: 'http:localhost:8081'
  players-service: 'http://localhost:8082'

aws:
  sqs:
    accessKeyId: 123
    secretAccessKey: 123
    host: http://localhost:4566
    region: eu-west-1
    queues:
      player-bought-queue-url: http://localhost:4566/000000000000/PlayerBoughtQueueURL.fifo
