server:
  port: ${SERVER_PORT}

spring:

  application:
    profiles:
      active: 'dev'

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

aws:
  sqs:
    accessKeyId: ${AWS_SQS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SQS_SECRET_ACCESS_KEY}
    host: ${AWS_SQS_HOST}
    region: ${AWS_SQS_REGION}
    queues:
      user-signed-up-queue-url: ${AWS_SQS_USER_SIGNED_UP_QUEUE_URL}

security:
  oauth2:
    access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${REFRESH_TOKEN_VALIDITY_SECONDS}
    client-id: ${TOPTAL_CLIENT_ID}
    client-secret: ${TOPTAL_CLIENT_SECRET}
    public-key: ${TOPTAL_PUBLIC_KEY}
    private-key: ${TOPTAL_PRIVATE_KEY}
