
@startuml Sign Up

header Sign Up

actor "user"

activate "gateway-service" #4db9f7
"user" -> "gateway-service": SignUp
activate "auth-service" #ff3355
"gateway-service" -> "auth-service": SignUp
database "auth-service-db"
"auth-service" -> "auth-service-db": Stores the user account
queue "Queue system"
"auth-service" -> "Queue system": Fires UserSignedUpEvent
"auth-service" --> "gateway-service": 201 HTTP
deactivate "auth-service" 
"gateway-service" --> "user": 201 HTTP
deactivate "gateway-service" 

@enduml
 