server:
  port: 8082
  servlet:
    context-path: /players-service

spring:

  application:
    name: players-service
    profiles:
      active: 'local'

  data:
    mongodb:
      uri: mongodb://test123:test123@localhost:27018/players-service-db

hosts:
  auth-service: 'http:localhost:8081'

aws:
  sqs:
    accessKeyId: 123
    secretAccessKey: 123
    host: http://localhost:4566
    region: eu-west-1
    queues:
      user-signed-up-queue-url: http://localhost:4566/000000000000/UserSignedUpQueueURL
      player-bought-queue-url: http://localhost:4566/000000000000/PlayerBoughtQueueURL.fifo

security:
  oauth2:
    client-id: toptal-client-id
    client-secret: toptal-client-secret