server:
  port: ${SERVER_PORT}

spring:

  application:
    profiles:
      active: 'dev'

  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}

aws:
  sqs:
    accessKeyId: ${AWS_SQS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SQS_SECRET_ACCESS_KEY}
    host: ${AWS_SQS_HOST}
    region: ${AWS_SQS_REGION}
    queues:
      user-signed-up-queue-url: ${AWS_SQS_USER_SIGNED_UP_QUEUE_URL}
