
@startuml Update Player

header Update Player

actor "user"

activate "gateway-service" #4db9f7
"user" -> "gateway-service": PUT HTTP - update player
activate "players-service" #ff3355
"gateway-service" -> "players-service": PUT HTTP - update player
database "players-service-db"
"players-service" -> "players-service-db": Update the player in the DB
"players-service" --> "gateway-service": 200 HTTP
deactivate "players-service" 
"gateway-service" --> "user": 200 HTTP
deactivate "gateway-service" 

@enduml
 