server:
  port: ${SERVER_PORT}

spring:

  application:
    profiles:
      active: 'dev'

hosts:
  auth-service: 'http://${AUTH_SERVICE_HOST}'
  players-service: 'http://${PLAYERS_SERVICE_HOST}'
  market-service: 'http://${MARKET_SERVICE_HOST}'

zuul:
  sensitive-headers:
  routes:
    auth-service:
      path: /auth-service/**
      url: ${hosts.auth-service}/auth-service
    players-service:
      path: /players-service/**
      url: ${hosts.players-service}/players-service
    market-service:
      path: /market-service/**
      url: ${hosts.market-service}/market-service

security:
  oauth2:
    resource:
      jwt:
        key-uri: ${hosts.auth-service}/auth-service/oauth/token_key

