version: '3.9'

services:

  # Local Stack (AWS local)
  localstack:
    image: localstack/localstack:0.12.18
    ports:
      - "4566:4566"
    container_name: localstack
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstackdata:/tmp/localstack"

  # Auth Service DB
  auth-service-db:
    container_name: auth-service-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth-service-db
      POSTGRES_USER: test123
      POSTGRES_PASSWORD: test123
    volumes:
      - db-data:/var/lib/postgresql/data

  # Auth Service
  auth-service:
    image: maven:3.6.3-openjdk-11
    ports:
      - 8081:8081
    container_name: auth-service
    env_file:
      - ../config/common.env
      - ../config/auth.env
    volumes:
      - ${M2_PATH}:/root/.m2
      - ../../auth-service:/auth-service
    working_dir: /auth-service
    command: mvn compile spring-boot:run -DskipTests=true

  # Players Service DB
  players-service-db:
    image: bitnami/mongodb:5.0.3
    ports:
      - 27018:27018
    container_name: players-service-db
    env_file:
      - ../config/players.env
    volumes:
      - mongodb-players-service-data:/data/db
    environment:
      - MONGODB_PORT_NUMBER=27018
      - MONGODB_USERNAME=test123
      - MONGODB_PASSWORD=test123
      - MONGODB_DATABASE=players-service-db

  # Players Service
  players-service:
    image: maven:3.6.3-openjdk-11
    ports:
      - 8082:8082
    container_name: players-service
    env_file:
      - ../config/common.env
      - ../config/players.env
    volumes:
      - ${M2_PATH}:/root/.m2
      - ../../players-service:/players-service
    working_dir: /players-service
    command: mvn compile spring-boot:run -DskipTests=true

# Volumes
volumes:
  db-data:
  localstackdata:
  mongodb-players-service-data:

